# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from os import path
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuStackedWidget(object):
    def setupUi(self, MenuStackedWidget):
        MenuStackedWidget.setObjectName("MenuStackedWidget")
        MenuStackedWidget.resize(832, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/icon/Icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MenuStackedWidget.setWindowIcon(icon)
        MenuStackedWidget.setStyleSheet("")
        self.Menu = QtWidgets.QWidget()
        self.Menu.setStyleSheet("background-image: url(:/Menu/Background.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.Menu.setObjectName("Menu")
        self.ButtonStart = QtWidgets.QPushButton(self.Menu)
        self.ButtonStart.setGeometry(QtCore.QRect(266, 600, 300, 140))
        self.ButtonStart.setStyleSheet("background-image: url(:/Menu/Start.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.ButtonStart.setText("")
        self.ButtonStart.setObjectName("ButtonStart")
        MenuStackedWidget.addWidget(self.Menu)
        self.Game = QtWidgets.QWidget()
        self.Game.setStyleSheet("background-image: url(:/Game/GameBackGround.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.Game.setObjectName("Game")
        self.StoneCount = QtWidgets.QLabel(self.Game)
        self.StoneCount.setGeometry(QtCore.QRect(390, 710, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(72)
        self.StoneCount.setFont(font)
        self.StoneCount.setAutoFillBackground(False)
        self.StoneCount.setStyleSheet("background-image: url(\"\");\n"
"color: rgb(163, 152, 31);")
        self.StoneCount.setObjectName("StoneCount")
        self.ButtonTakeStone = QtWidgets.QPushButton(self.Game)
        self.ButtonTakeStone.setGeometry(QtCore.QRect(250, 460, 361, 231))
        self.ButtonTakeStone.setStyleSheet("background-image: url(:/Game/TakeStone.png);")
        self.ButtonTakeStone.setText("")
        self.ButtonTakeStone.setObjectName("ButtonTakeStone")
        self.PlayerNumber = QtWidgets.QLabel(self.Game)
        self.PlayerNumber.setGeometry(QtCore.QRect(730, 170, 51, 81))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text Semilight")
        font.setPointSize(72)
        self.PlayerNumber.setFont(font)
        self.PlayerNumber.setAutoFillBackground(False)
        self.PlayerNumber.setStyleSheet("background-image: url(\"\");\n"
"color: rgb(163, 152, 31);")
        self.PlayerNumber.setObjectName("PlayerNumber")
        self.Select1Stone = QtWidgets.QPushButton(self.Game)
        self.Select1Stone.setGeometry(QtCore.QRect(250, 330, 91, 91))
        self.Select1Stone.setStyleSheet("background-image: url(:/Game/Select1Stone.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.Select1Stone.setText("")
        self.Select1Stone.setObjectName("Select1Stone")
        self.Select2Stone = QtWidgets.QPushButton(self.Game)
        self.Select2Stone.setGeometry(QtCore.QRect(380, 330, 91, 91))
        self.Select2Stone.setStyleSheet("background-image: url(:/Game/Select2Stone.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.Select2Stone.setText("")
        self.Select2Stone.setObjectName("Select2Stone")
        self.Select3Stone = QtWidgets.QPushButton(self.Game)
        self.Select3Stone.setGeometry(QtCore.QRect(520, 330, 91, 91))
        self.Select3Stone.setStyleSheet("background-image: url(:/Game/Select3Stone.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.Select3Stone.setText("")
        self.Select3Stone.setObjectName("Select3Stone")
        MenuStackedWidget.addWidget(self.Game)
        self.LoseScreen = QtWidgets.QWidget()
        self.LoseScreen.setStyleSheet("background-image: url(:/WinScreenPlayer2/LoseScreen.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.LoseScreen.setObjectName("LoseScreen")
        MenuStackedWidget.addWidget(self.LoseScreen)
        self.WinScreen = QtWidgets.QWidget()
        self.WinScreen.setStyleSheet("background-image: url(:/WinScreenPlayer1/WinScreen.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.WinScreen.setObjectName("WinScreen")
        MenuStackedWidget.addWidget(self.WinScreen)

        self.retranslateUi(MenuStackedWidget)
        QtCore.QMetaObject.connectSlotsByName(MenuStackedWidget)

    def retranslateUi(self, MenuStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        MenuStackedWidget.setWindowTitle(_translate("MenuStackedWidget", "nim-game"))
        self.StoneCount.setText(_translate("MenuStackedWidget", "15"))
        self.PlayerNumber.setText(_translate("MenuStackedWidget", "1"))
import resources_rc
